import { db } from '@/db';
import { gallery } from '@/db/schema';

async function main() {
    const currentTimestamp = new Date().toISOString();
    
    const sampleGallery = [
        {
            titleEn: 'Modern Office LED Ceiling',
            titleFr: 'Plafond LED Bureau Moderne',
            titleAr: 'سقف LED مكتب حديث',
            descriptionEn: 'Professional LED ceiling panel installation in a modern corporate office space, providing energy-efficient and ambient lighting throughout the workspace.',
            descriptionFr: 'Installation professionnelle de panneaux LED au plafond dans un espace de bureau moderne, offrant un éclairage ambiant et économe en énergie dans tout l\'espace de travail.',
            descriptionAr: 'تركيب احترافي لألواح LED في سقف مكتب شركة حديث، يوفر إضاءة محيطة وموفرة للطاقة في جميع أنحاء مساحة العمل.',
            beforeImageUrl: '/images/gallery/project-1-before.jpg',
            afterImageUrl: '/images/gallery/project-1-after.jpg',
            category: 'led-panels',
            orderIndex: 1,
            isFeatured: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: 'Restaurant Ambient Lighting',
            titleFr: 'Éclairage Ambiant Restaurant',
            titleAr: 'إضاءة محيطة للمطعم',
            descriptionEn: 'Sophisticated LED panel lighting system designed to create the perfect dining atmosphere, with adjustable color temperature and dimming capabilities.',
            descriptionFr: 'Système d\'éclairage LED sophistiqué conçu pour créer l\'atmosphère de restauration parfaite, avec température de couleur réglable et capacités de gradation.',
            descriptionAr: 'نظام إضاءة LED متطور مصمم لخلق جو مثالي لتناول الطعام، مع درجة حرارة لون قابلة للتعديل وإمكانيات تعتيم.',
            beforeImageUrl: '/images/gallery/project-2-before.jpg',
            afterImageUrl: '/images/gallery/project-2-after.jpg',
            category: 'led-panels',
            orderIndex: 2,
            isFeatured: false,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: 'Retail Store LED Display',
            titleFr: 'Affichage LED Magasin',
            titleAr: 'عرض LED متجر التجزئة',
            descriptionEn: 'Dynamic LED panel installation for retail environment, enhancing product visibility and creating an engaging shopping experience with uniform, high-quality lighting.',
            descriptionFr: 'Installation dynamique de panneaux LED pour environnement de vente au détail, améliorant la visibilité des produits et créant une expérience d\'achat engageante avec un éclairage uniforme de haute qualité.',
            descriptionAr: 'تركيب ديناميكي لألواح LED لبيئة البيع بالتجزئة، يعزز رؤية المنتج ويخلق تجربة تسوق جذابة مع إضاءة موحدة عالية الجودة.',
            beforeImageUrl: '/images/gallery/project-3-before.jpg',
            afterImageUrl: '/images/gallery/project-3-after.jpg',
            category: 'led-panels',
            orderIndex: 3,
            isFeatured: false,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: 'Hotel Lobby Lighting',
            titleFr: 'Éclairage Hall Hôtel',
            titleAr: 'إضاءة ردهة الفندق',
            descriptionEn: 'Luxurious LED panel lighting installation in hotel lobby, combining elegance with functionality to create a welcoming and impressive first impression for guests.',
            descriptionFr: 'Installation d\'éclairage LED luxueuse dans le hall de l\'hôtel, combinant élégance et fonctionnalité pour créer une première impression accueillante et impressionnante pour les clients.',
            descriptionAr: 'تركيب إضاءة LED فاخر في ردهة الفندق، يجمع بين الأناقة والوظائف لخلق انطباع أول ترحيبي ومثير للإعجاب للضيوف.',
            beforeImageUrl: '/images/gallery/project-4-before.jpg',
            afterImageUrl: '/images/gallery/project-4-after.jpg',
            category: 'led-panels',
            orderIndex: 4,
            isFeatured: false,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: '3D Geometric Wall Art',
            titleFr: 'Art Mural Géométrique 3D',
            titleAr: 'فن جداري هندسي ثلاثي الأبعاد',
            descriptionEn: 'Stunning 3D decorative wall panels featuring intricate geometric patterns, adding depth and visual interest to modern interior spaces with contemporary design elements.',
            descriptionFr: 'Superbes panneaux muraux décoratifs 3D présentant des motifs géométriques complexes, ajoutant profondeur et intérêt visuel aux espaces intérieurs modernes avec des éléments de design contemporain.',
            descriptionAr: 'ألواح جدارية ثلاثية الأبعاد مذهلة تتميز بأنماط هندسية معقدة، تضيف عمقًا واهتمامًا بصريًا للمساحات الداخلية الحديثة مع عناصر تصميم معاصرة.',
            beforeImageUrl: '/images/gallery/project-5-before.jpg',
            afterImageUrl: '/images/gallery/project-5-after.jpg',
            category: '3d-decoration',
            orderIndex: 5,
            isFeatured: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: 'Living Room Feature Wall',
            titleFr: 'Mur d\'Accent Salon',
            titleAr: 'جدار مميز لغرفة المعيشة',
            descriptionEn: 'Elegant 3D textured wall panel installation for residential living room, creating a sophisticated focal point that combines artistic design with architectural beauty.',
            descriptionFr: 'Installation élégante de panneaux muraux texturés 3D pour salon résidentiel, créant un point focal sophistiqué qui combine design artistique et beauté architecturale.',
            descriptionAr: 'تركيب أنيق لألواح جدارية ثلاثية الأبعاد لغرفة المعيشة السكنية، يخلق نقطة محورية متطورة تجمع بين التصميم الفني والجمال المعماري.',
            beforeImageUrl: '/images/gallery/project-6-before.jpg',
            afterImageUrl: '/images/gallery/project-6-after.jpg',
            category: '3d-decoration',
            orderIndex: 6,
            isFeatured: false,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: 'Corporate Office Entrance',
            titleFr: 'Entrée Bureau Corporate',
            titleAr: 'مدخل المكتب الشركة',
            descriptionEn: 'Impressive 3D branding wall installation at corporate office entrance, featuring company logo and brand elements with dimensional design that creates lasting impressions.',
            descriptionFr: 'Installation impressionnante de mur de marque 3D à l\'entrée du bureau corporatif, présentant le logo et les éléments de marque avec un design dimensionnel qui crée des impressions durables.',
            descriptionAr: 'تركيب جداري ثلاثي الأبعاد مثير للإعجاب لعلامة تجارية في مدخل المكتب الشركة، يتميز بشعار الشركة وعناصر العلامة التجارية بتصميم بعدي يخلق انطباعات دائمة.',
            beforeImageUrl: '/images/gallery/project-7-before.jpg',
            afterImageUrl: '/images/gallery/project-7-after.jpg',
            category: '3d-decoration',
            orderIndex: 7,
            isFeatured: false,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: 'Cafe Interior Design',
            titleFr: 'Design Intérieur Café',
            titleAr: 'تصميم داخلي للمقهى',
            descriptionEn: 'Creative 3D wall decoration for cafe interior, combining modern aesthetics with comfortable ambiance to create an inviting space that encourages social interaction.',
            descriptionFr: 'Décoration murale 3D créative pour intérieur de café, combinant esthétique moderne et ambiance confortable pour créer un espace accueillant qui encourage l\'interaction sociale.',
            descriptionAr: 'ديكور جداري ثلاثي الأبعاد إبداعي للمقهى الداخلي، يجمع بين الجماليات الحديثة والأجواء المريحة لخلق مساحة جذابة تشجع التفاعل الاجتماعي.',
            beforeImageUrl: '/images/gallery/project-8-before.jpg',
            afterImageUrl: '/images/gallery/project-8-after.jpg',
            category: '3d-decoration',
            orderIndex: 8,
            isFeatured: false,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: 'Wedding Venue Decoration',
            titleFr: 'Décoration Lieu Mariage',
            titleAr: 'تزيين مكان الزفاف',
            descriptionEn: 'Magical wedding venue transformation using LED lighting and 3D decorative elements, creating a romantic and unforgettable atmosphere for the special celebration.',
            descriptionFr: 'Transformation magique du lieu de mariage utilisant l\'éclairage LED et des éléments décoratifs 3D, créant une atmosphère romantique et inoubliable pour la célébration spéciale.',
            descriptionAr: 'تحول سحري لمكان الزفاف باستخدام إضاءة LED وعناصر زخرفية ثلاثية الأبعاد، يخلق جوًا رومانسيًا لا يُنسى للاحتفال الخاص.',
            beforeImageUrl: '/images/gallery/project-9-before.jpg',
            afterImageUrl: '/images/gallery/project-9-after.jpg',
            category: 'events',
            orderIndex: 9,
            isFeatured: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: 'Corporate Event Backdrop',
            titleFr: 'Toile de Fond Événement',
            titleAr: 'خلفية الحدث الشركة',
            descriptionEn: 'Professional event backdrop design featuring integrated LED lighting, creating a stunning visual impact for corporate presentations, product launches, and business conferences.',
            descriptionFr: 'Design professionnel de toile de fond d\'événement avec éclairage LED intégré, créant un impact visuel époustouflant pour présentations corporatives, lancements de produits et conférences d\'affaires.',
            descriptionAr: 'تصميم احترافي لخلفية الحدث يتميز بإضاءة LED متكاملة، يخلق تأثيرًا بصريًا مذهلاً للعروض التقديمية الشركة وإطلاق المنتجات والمؤتمرات التجارية.',
            beforeImageUrl: '/images/gallery/project-10-before.jpg',
            afterImageUrl: '/images/gallery/project-10-after.jpg',
            category: 'events',
            orderIndex: 10,
            isFeatured: false,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: 'Exhibition Stand Design',
            titleFr: 'Stand Exposition Design',
            titleAr: 'تصميم جناح المعرض',
            descriptionEn: 'Custom exhibition stand featuring 3D architectural elements and strategic LED lighting, designed to attract visitors and showcase products effectively at trade shows.',
            descriptionFr: 'Stand d\'exposition personnalisé avec éléments architecturaux 3D et éclairage LED stratégique, conçu pour attirer les visiteurs et présenter efficacement les produits lors des salons professionnels.',
            descriptionAr: 'جناح معرض مخصص يتميز بعناصر معمارية ثلاثية الأبعاد وإضاءة LED استراتيجية، مصمم لجذب الزوار وعرض المنتجات بفعالية في المعارض التجارية.',
            beforeImageUrl: '/images/gallery/project-11-before.jpg',
            afterImageUrl: '/images/gallery/project-11-after.jpg',
            category: 'events',
            orderIndex: 11,
            isFeatured: false,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            titleEn: 'Custom Neon Sign Installation',
            titleFr: 'Installation Enseigne Néon',
            titleAr: 'تركيب لافتة نيون مخصصة',
            descriptionEn: 'Bespoke neon signage installation project combining traditional neon craftsmanship with modern LED technology, creating eye-catching displays for businesses and brands.',
            descriptionFr: 'Projet d\'installation d\'enseigne au néon sur mesure combinant l\'artisanat néon traditionnel avec la technologie LED moderne, créant des affichages accrocheurs pour les entreprises et les marques.',
            descriptionAr: 'مشروع تركيب لافتات نيون مخصصة يجمع بين حرفية النيون التقليدية وتقنية LED الحديثة، يخلق عروضًا لافتة للنظر للشركات والعلامات التجارية.',
            beforeImageUrl: '/images/gallery/project-12-before.jpg',
            afterImageUrl: '/images/gallery/project-12-after.jpg',
            category: 'other',
            orderIndex: 12,
            isFeatured: true,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(gallery).values(sampleGallery);
    
    console.log('✅ Gallery seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});